name: ci

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'source/CODE.md'
      - 'source/docs/**'

  workflow_dispatch:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup rust
        run: |
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
      - name: check cargo fmt
        working-directory: ./source
        run: |
          . ../tools/activate
          vargo fmt -- --check

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ['', 'singular']
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: get z3
        working-directory: ./source
        run: |
          ../.github/workflows/get-z3.sh
          echo z3 version `./z3 --version`
      - name: setup rust
        run: |
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
      - name: setup singular
        if: matrix.features == 'singular'
        run: |
          sudo apt-get update
          sudo apt-get install -y singular 
      - name: cargo test
        working-directory: ./source
        run: |
          . ../tools/activate
          vargo clean
          if [ "${{ matrix.features }}" == "singular" ]; then
            vargo build --features singular
            VERUS_Z3_PATH="$(pwd)/z3" vargo test -p air --features singular
            VERUS_Z3_PATH="$(pwd)/z3" vargo test -p rust_verify_test --features singular
          else
            vargo build
            VERUS_Z3_PATH="$(pwd)/z3" vargo test -p air
            VERUS_Z3_PATH="$(pwd)/z3" vargo test -p rust_verify_test
          fi
