name: ci

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'source/CODE.md'
      - 'source/docs/**'

  workflow_dispatch:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: check cargo fmt
        working-directory: ./source
        run: |
          export PATH=/home/chanheec/.cargo/bin/:$PATH
          . ../tools/activate
          vargo fmt -- --check

  test:
    runs-on: self-hosted
    strategy:
      matrix:
        features: ['', 'singular']
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: get z3
        working-directory: ./source
        run: |
          ../.github/workflows/get-z3.sh
          echo z3 version `./z3 --version`
      - name: cargo test
        working-directory: ./source
        run: |
          export PATH=/home/chanheec/.cargo/bin/:$PATH
          . ../tools/activate
          vargo clean
          if [ "${{ matrix.features }}" == "singular" ]; then
            vargo build --features singular
            VERUS_Z3_PATH="$(pwd)/z3" vargo test --features singular
          else
            vargo build
            VERUS_Z3_PATH="$(pwd)/z3" vargo test
          fi
